/**
 * ExamenTec API
 *
 * Contact: support@examentec.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryLookupDto } from './categoryLookupDto';
import { HttpStatusCode } from './httpStatusCode';


export interface CategoryLookupDtoIEnumerableHttpResponse { 
    readonly result?: Array<CategoryLookupDto> | null;
    readonly message?: string | null;
    statusCode?: HttpStatusCode;
    readonly isError?: boolean;
}
export namespace CategoryLookupDtoIEnumerableHttpResponse {
}


