/**
 * ExamenTec API
 *
 * Contact: support@examentec.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogDto { 
    id?: string;
    timestamp?: string;
    level?: string | null;
    message?: string | null;
    exception?: string | null;
    source?: string | null;
    method?: string | null;
    user?: string | null;
    requestPath?: string | null;
    statusCode?: number | null;
}

